# Generated by Django 2.1.8 on 2019-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0007_krill_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='altr_view',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='krill',
            name='board',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='krill',
            name='dorsal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='krill',
            name='event',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='krill',
            name='lateral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='krill',
            name='net',
            field=models.CharField(default='', max_length=50),
        ),
    ]
