# Generated by Django 2.2.7 on 2020-01-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0008_auto_20191212_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='board',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='net',
            field=models.CharField(default='', max_length=30),
        ),
    ]
