# Generated by Django 3.0.2 on 2020-01-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0009_auto_20200118_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.TextField(default=''),
        ),
    ]
