# Generated by Django 3.0.2 on 2020-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrillApp', '0010_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='krill',
            name='position',
            field=models.TextField(default=''),
        ),
    ]
